-- Create payment_transactions table for logging all payment activities
CREATE TABLE IF NOT EXISTS payment_transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_email TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  reference TEXT NOT NULL UNIQUE,
  lenco_reference TEXT,
  status TEXT NOT NULL, -- 'pending', 'successful', 'failed'
  payment_type TEXT, -- 'card', 'mobile-money'
  fee DECIMAL(10,2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_payment_transactions_user_email ON payment_transactions(user_email);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_reference ON payment_transactions(reference);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_status ON payment_transactions(status);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_created_at ON payment_transactions(created_at);

-- Enable RLS
ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own transactions" ON payment_transactions
  FOR SELECT USING (
    auth.uid() IS NOT NULL AND 
    user_email = (SELECT email FROM users WHERE id = auth.uid())
  );

CREATE POLICY "System can insert transactions" ON payment_transactions
  FOR INSERT WITH CHECK (true);

-- Only allow system updates (for webhook processing)
CREATE POLICY "System can update transactions" ON payment_transactions
  FOR UPDATE WITH CHECK (true);

-- Add comments
COMMENT ON TABLE payment_transactions IS 'Logs all payment transactions processed through Lenco';
COMMENT ON COLUMN payment_transactions.user_email IS 'Email of the user who made the payment';
COMMENT ON COLUMN payment_transactions.reference IS 'Unique reference generated by our system';
COMMENT ON COLUMN payment_transactions.lenco_reference IS 'Reference generated by Lenco';
COMMENT ON COLUMN payment_transactions.status IS 'Current status of the transaction';
COMMENT ON COLUMN payment_transactions.payment_type IS 'Type of payment method used';
